# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 인스타그램 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Node.js ${{ matrix.node-version }} 설치 👍👍
      uses: actions/setup-node@v2

    - name: MariaDB 설치 💕😂
      uses: getong/mariadb-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mariadb version: '10.4.10'
        mysql database: 'vanila-instagram'
        mysql root password: 'sungsimdang12'
        mysql user: 'user'
        mysql password: 'sungsimdang'

    - name: npm ci 모드 실행 😎
      run: npm ci

    - name: 서버 환경설정 파일 복사 💥
      run: pwd && cp .env.example .env
      working-directory: ${{ env.SERVER }}

    - name: 프런트엔드 패키지 설치 🔰
      run: npm ci
      working-directory: ${{ env.CLIENT }}

    - name: 백엔드 패키지 설치 🔰
      run: npm install
      working-directory: ${{ env.BACKEND }}

    - name: 서버 ESLint 검사 😒
      run: npm run lint
      working-directory: ${{ env.SERVER }}

    env:
      ROOT: '/home/runner/work/vanilla-instagram/vanilla-instagram'
      CLIENT: '/home/runner/work/vanilla-instagram/vanilla-instagram/client'
      SERVER: '/home/runner/work/vanilla-instagram/vanilla-instagram/server'